// <auto-generated />
using System;
using Insurance.Hiring.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Insurance.Hiring.Infra.Migrations
{
    [DbContext(typeof(ContractDbContext))]
    [Migration("20250730153844_UpdateContract")]
    partial class UpdateContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("insurance")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Insurance.Hiring.Domain.Domain.ContractEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contract_date");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("coverage_amount");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.ToTable("contracts", "insurance");
                });
#pragma warning restore 612, 618
        }
    }
}
